# Generated by Django 5.2.7 on 2025-11-12 06:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('compliance', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='complianceaudit',
            new_name='compliance__organiz_61397a_idx',
            old_name='compliance_organiz_0_idx',
        ),
        migrations.RenameIndex(
            model_name='complianceaudit',
            new_name='compliance__status_3c82ac_idx',
            old_name='compliance_status_1_idx',
        ),
        migrations.RenameIndex(
            model_name='violationreport',
            new_name='compliance__organiz_ed4b60_idx',
            old_name='compliance_organiz_2_idx',
        ),
        migrations.RenameIndex(
            model_name='violationreport',
            new_name='compliance__violati_9950b6_idx',
            old_name='compliance_violati_3_idx',
        ),
    ]
