# Generated by Django 5.2.7 on 2025-11-12 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0006_integrityrecord'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='org',
            options={'ordering': ['-trust_score', 'name']},
        ),
        migrations.RenameIndex(
            model_name='integrityrecord',
            new_name='organizatio_organiz_d98c91_idx',
            old_name='organization_organiz_2_idx',
        ),
        migrations.RenameIndex(
            model_name='integrityrecord',
            new_name='organizatio_entity__e2e09e_idx',
            old_name='organization_entity__3_idx',
        ),
        migrations.RenameIndex(
            model_name='org',
            new_name='organizatio_trust_s_15dc8d_idx',
            old_name='organization_trust_s_0_idx',
        ),
        migrations.RenameIndex(
            model_name='org',
            new_name='organizatio_trust_l_f1b90c_idx',
            old_name='organization_trust_l_1_idx',
        ),
        migrations.AlterField(
            model_name='org',
            name='trust_score',
            field=models.FloatField(blank=True, default=0.0, help_text='Overall trust score (0-100)', null=True),
        ),
    ]
