# Generated by Django 5.2.7 on 2025-11-12 06:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('consents', '0005_userconsent_expiry_history'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='consenthistory',
            new_name='consents_co_user_co_a4cf04_idx',
            old_name='consents_con_user_co_2_idx',
        ),
        migrations.RenameIndex(
            model_name='consenthistory',
            new_name='consents_co_action_b7ec35_idx',
            old_name='consents_con_action_3_idx',
        ),
        migrations.RenameIndex(
            model_name='userconsent',
            new_name='consents_us_user_id_eb8866_idx',
            old_name='consents_use_user_id_0_idx',
        ),
        migrations.RenameIndex(
            model_name='userconsent',
            new_name='consents_us_expires_e20c4a_idx',
            old_name='consents_use_expires_1_idx',
        ),
    ]
