# Generated by Django 5.2.7 on 2025-11-15 13:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('consents', '0006_rename_consents_con_user_co_2_idx_consents_co_user_co_a4cf04_idx_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='userconsent',
            unique_together=set(),
        ),
    ]
