# Generated by Django 5.2.7 on 2025-11-18 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consents', '0007_alter_userconsent_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userconsent',
            name='granted_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
