# Generated by Django 5.2.7 on 2025-12-13 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consents', '0008_alter_userconsent_granted_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userconsent',
            name='granted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
